# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectClassInputFeatures.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_inputFeatures(object):
    def setupUi(self, inputFeatures):
        inputFeatures.setObjectName("inputFeatures")
        inputFeatures.resize(800, 590)
        inputFeatures.setMinimumSize(QtCore.QSize(800, 590))
        inputFeatures.setMaximumSize(QtCore.QSize(800, 590))
        self.centralwidget = QtWidgets.QWidget(inputFeatures)
        self.centralwidget.setObjectName("centralwidget")
        self.button_ok_inputFeatures = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok_inputFeatures.setGeometry(QtCore.QRect(660, 500, 102, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_ok_inputFeatures.setFont(font)
        self.button_ok_inputFeatures.setObjectName("button_ok_inputFeatures")
        self.button_goBack_inputFeatures = QtWidgets.QPushButton(self.centralwidget)
        self.button_goBack_inputFeatures.setGeometry(QtCore.QRect(40, 500, 102, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_goBack_inputFeatures.setFont(font)
        self.button_goBack_inputFeatures.setObjectName("button_goBack_inputFeatures")
        self.text_featuresList_inputFeatures = QtWidgets.QTextEdit(self.centralwidget)
        self.text_featuresList_inputFeatures.setGeometry(QtCore.QRect(33, 109, 441, 341))
        self.text_featuresList_inputFeatures.setReadOnly(True)
        self.text_featuresList_inputFeatures.setObjectName("text_featuresList_inputFeatures")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(500, 130, 291, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_addFeature_inputFeatures = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_addFeature_inputFeatures.setFont(font)
        self.button_addFeature_inputFeatures.setObjectName("button_addFeature_inputFeatures")
        self.verticalLayout.addWidget(self.button_addFeature_inputFeatures)
        self.comboBox_addFeature_inputFeatures = QtWidgets.QComboBox(self.widget)
        self.comboBox_addFeature_inputFeatures.setObjectName("comboBox_addFeature_inputFeatures")
        self.verticalLayout.addWidget(self.comboBox_addFeature_inputFeatures)
        self.button_deleteFeature_inputFeatures = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_deleteFeature_inputFeatures.setFont(font)
        self.button_deleteFeature_inputFeatures.setObjectName("button_deleteFeature_inputFeatures")
        self.verticalLayout.addWidget(self.button_deleteFeature_inputFeatures)
        self.comboBox_deleteFeature_inputFeatures = QtWidgets.QComboBox(self.widget)
        self.comboBox_deleteFeature_inputFeatures.setObjectName("comboBox_deleteFeature_inputFeatures")
        self.verticalLayout.addWidget(self.comboBox_deleteFeature_inputFeatures)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(31, 51, 531, 52))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        inputFeatures.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(inputFeatures)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        inputFeatures.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(inputFeatures)
        self.statusbar.setObjectName("statusbar")
        inputFeatures.setStatusBar(self.statusbar)

        self.retranslateUi(inputFeatures)
        QtCore.QMetaObject.connectSlotsByName(inputFeatures)

    def retranslateUi(self, inputFeatures):
        _translate = QtCore.QCoreApplication.translate
        inputFeatures.setWindowTitle(_translate("inputFeatures", "Определение класса электроники. Выбор признаков"))
        self.button_ok_inputFeatures.setText(_translate("inputFeatures", "ОК"))
        self.button_goBack_inputFeatures.setText(_translate("inputFeatures", "Вернуться"))
        self.button_addFeature_inputFeatures.setText(_translate("inputFeatures", "Добавить признак"))
        self.button_deleteFeature_inputFeatures.setText(_translate("inputFeatures", "Удалить признак"))
        self.label_3.setText(_translate("inputFeatures", "Введите признаки для ввода исходных данных"))
        self.label_2.setText(_translate("inputFeatures", "Список признаков для ввода исходных данных"))

