# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectClassSetFeature.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_setFeature(object):
    def setupUi(self, setFeature):
        setFeature.setObjectName("setFeature")
        setFeature.resize(800, 565)
        setFeature.setMinimumSize(QtCore.QSize(800, 565))
        setFeature.setMaximumSize(QtCore.QSize(800, 565))
        self.centralwidget = QtWidgets.QWidget(setFeature)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(32, 70, 411, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.comboBox_featureChoose_setFeature = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_featureChoose_setFeature.setObjectName("comboBox_featureChoose_setFeature")
        self.verticalLayout_6.addWidget(self.comboBox_featureChoose_setFeature)
        self.button_featureSet_setFeature = QtWidgets.QPushButton(self.centralwidget)
        self.button_featureSet_setFeature.setGeometry(QtCore.QRect(640, 77, 110, 52))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_featureSet_setFeature.setFont(font)
        self.button_featureSet_setFeature.setObjectName("button_featureSet_setFeature")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(400, 150, 351, 222))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.text_featureUnset_setFeature = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.text_featureUnset_setFeature.setReadOnly(True)
        self.text_featureUnset_setFeature.setObjectName("text_featureUnset_setFeature")
        self.verticalLayout_2.addWidget(self.text_featureUnset_setFeature)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(452, 75, 181, 55))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.line_featureType_setFeature = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.line_featureType_setFeature.setReadOnly(True)
        self.line_featureType_setFeature.setObjectName("line_featureType_setFeature")
        self.verticalLayout_4.addWidget(self.line_featureType_setFeature)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(34, 150, 361, 222))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.text_featureSet_setFeature = QtWidgets.QTextEdit(self.layoutWidget_5)
        self.text_featureSet_setFeature.setReadOnly(True)
        self.text_featureSet_setFeature.setObjectName("text_featureSet_setFeature")
        self.verticalLayout_3.addWidget(self.text_featureSet_setFeature)
        self.button_goBack_setFeature = QtWidgets.QPushButton(self.centralwidget)
        self.button_goBack_setFeature.setGeometry(QtCore.QRect(20, 480, 102, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_goBack_setFeature.setFont(font)
        self.button_goBack_setFeature.setObjectName("button_goBack_setFeature")
        self.button_ok_setFeature = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok_setFeature.setGeometry(QtCore.QRect(660, 480, 102, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_ok_setFeature.setFont(font)
        self.button_ok_setFeature.setObjectName("button_ok_setFeature")
        setFeature.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(setFeature)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        setFeature.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(setFeature)
        self.statusbar.setObjectName("statusbar")
        setFeature.setStatusBar(self.statusbar)

        self.retranslateUi(setFeature)
        QtCore.QMetaObject.connectSlotsByName(setFeature)

    def retranslateUi(self, setFeature):
        _translate = QtCore.QCoreApplication.translate
        setFeature.setWindowTitle(_translate("setFeature", "Определение класса электротехники. Установка значений признаков"))
        self.label_5.setText(_translate("setFeature", "Выберите признак"))
        self.button_featureSet_setFeature.setText(_translate("setFeature", "Установить\n"
" значение"))
        self.label_7.setText(_translate("setFeature", "Список не определенных признаков"))
        self.label_3.setText(_translate("setFeature", "Тип признака"))
        self.label_6.setText(_translate("setFeature", "Список определенных признаков"))
        self.button_goBack_setFeature.setText(_translate("setFeature", "Вернуться"))
        self.button_ok_setFeature.setText(_translate("setFeature", "ОК"))

