# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'knowledgeEditorClassExplanation.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_classExplanation(object):
    def setupUi(self, classExplanation):
        classExplanation.setObjectName("classExplanation")
        classExplanation.resize(800, 600)
        classExplanation.setMinimumSize(QtCore.QSize(800, 600))
        classExplanation.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(classExplanation)
        self.centralwidget.setObjectName("centralwidget")
        self.button_goBack_classExplanation = QtWidgets.QPushButton(self.centralwidget)
        self.button_goBack_classExplanation.setGeometry(QtCore.QRect(20, 510, 102, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_goBack_classExplanation.setFont(font)
        self.button_goBack_classExplanation.setObjectName("button_goBack_classExplanation")
        self.button_ok_classExplanation = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok_classExplanation.setGeometry(QtCore.QRect(670, 510, 102, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_ok_classExplanation.setFont(font)
        self.button_ok_classExplanation.setObjectName("button_ok_classExplanation")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 30, 681, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_classChoose_classExplanation = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_classChoose_classExplanation.setObjectName("comboBox_classChoose_classExplanation")
        self.verticalLayout.addWidget(self.comboBox_classChoose_classExplanation)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.text_featuresList_classExplanation = QtWidgets.QTextEdit(self.layoutWidget)
        self.text_featuresList_classExplanation.setReadOnly(True)
        self.text_featuresList_classExplanation.setObjectName("text_featuresList_classExplanation")
        self.verticalLayout_2.addWidget(self.text_featuresList_classExplanation)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_addFeature_classExplanation = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_addFeature_classExplanation.setFont(font)
        self.button_addFeature_classExplanation.setObjectName("button_addFeature_classExplanation")
        self.verticalLayout_3.addWidget(self.button_addFeature_classExplanation)
        self.comboBox_addFeature_classExplanation = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_addFeature_classExplanation.setObjectName("comboBox_addFeature_classExplanation")
        self.verticalLayout_3.addWidget(self.comboBox_addFeature_classExplanation)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_deleteFeature_classExplanation = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_deleteFeature_classExplanation.setFont(font)
        self.button_deleteFeature_classExplanation.setObjectName("button_deleteFeature_classExplanation")
        self.verticalLayout_4.addWidget(self.button_deleteFeature_classExplanation)
        self.comboBox_deleteFeature_classExplanation = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_deleteFeature_classExplanation.setFont(font)
        self.comboBox_deleteFeature_classExplanation.setObjectName("comboBox_deleteFeature_classExplanation")
        self.verticalLayout_4.addWidget(self.comboBox_deleteFeature_classExplanation)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_deleteAllFeatures_classExplanation = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_deleteAllFeatures_classExplanation.setFont(font)
        self.button_deleteAllFeatures_classExplanation.setObjectName("button_deleteAllFeatures_classExplanation")
        self.horizontalLayout.addWidget(self.button_deleteAllFeatures_classExplanation)
        self.button_addAllFeatures_classExplanation = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_addAllFeatures_classExplanation.setFont(font)
        self.button_addAllFeatures_classExplanation.setObjectName("button_addAllFeatures_classExplanation")
        self.horizontalLayout.addWidget(self.button_addAllFeatures_classExplanation)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        classExplanation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(classExplanation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        classExplanation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(classExplanation)
        self.statusbar.setObjectName("statusbar")
        classExplanation.setStatusBar(self.statusbar)

        self.retranslateUi(classExplanation)
        QtCore.QMetaObject.connectSlotsByName(classExplanation)

    def retranslateUi(self, classExplanation):
        _translate = QtCore.QCoreApplication.translate
        classExplanation.setWindowTitle(_translate("classExplanation", "Редактор знаний. Признаковое описание классов"))
        self.button_goBack_classExplanation.setText(_translate("classExplanation", "Вернуться"))
        self.button_ok_classExplanation.setText(_translate("classExplanation", "ОК"))
        self.label.setText(_translate("classExplanation", "Выберите класс"))
        self.label_2.setText(_translate("classExplanation", "Список признаков класса"))
        self.button_addFeature_classExplanation.setText(_translate("classExplanation", "Добавить признак"))
        self.button_deleteFeature_classExplanation.setText(_translate("classExplanation", "Удалить признак"))
        self.button_deleteAllFeatures_classExplanation.setText(_translate("classExplanation", "Удалить все \n"
" признаки"))
        self.button_addAllFeatures_classExplanation.setText(_translate("classExplanation", "Добавить все \n"
" признаки"))

